apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  USER_SERVICE_ADDR: "user-service:9091"
  TRIP_SERVICE_ADDR: "trip-service:9093"
