apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  USER_SERVICE_ADDR: "user-service:9091"
  TRIP_SERVICE_ADDR: "trip-service:9093"
  VITE_API_URL: "http://localhost:8081/api/v1"
  REDIS_ADDR: "redis:6379"
  AMQP_ADDR: "amqp://guest:guest@rabbitmq:5672"
